### ISSUE TITLE
Please make CookVSCode available on Open VSX Registry

### ISSUE THREAD

**Issue by Lonerider2010** [cooklang/CookVSCode#5]
As I use Codium instead of VSCode I try to use it independent from Microsoft. Therefore I use the [Open VSX Registry](https://open-vsx.org/) instead of the Visual Studio Marketplace. I am very interested in the cooklang environment, so I kindly ask you to publish your CookVSCode on the Open VSX Registry platform.
Thanks a lot.

**Comment by Lonerider2010** [comment]
If this is not possible, can you please provide the .vsix file? Tried to install CookVSCode on an arm64 system by building it with vsce, but this does not run on arm64.

**Comment by dubadub** [comment]
Done https://open-vsx.org/extension/dubadub/Cooklang. It will take some time to claim ownership.

**Comment by Lonerider2010** [comment]
Wow! That was really fast! Thansk a lot again.
And yes, it works!
Best regards,
